Added WPasswordEntry widget
pfalcon/picotui pull request #67
Opened 2021-11-21 19:18 UTC by timeopochin

Adds WPasswordEntry, a text entry widget that hides the typed text replacing it with `****`

2021-11-23 09:54 UTC, pfalcon requested changes
I try to keep Picotui lean and mean, and usually suggest to put additional widgets in seperate libraries. But if this is a 2-liner, why not?

But let's first make it 2-liner and follow the existing codebase conventions. Beyond the inline comments, please make sure that any fixup commit are squashed into the original commit, and please run `git log`, and follow the same commit message format for your commits.

Thanks!

2021-11-23 09:54 UTC, pfalcon commented on example_widgets.py
> +    d.add(1, 6, "Password:")
This change should be in a separate commit.

2021-11-23 09:54 UTC, pfalcon commented on picotui/widgets.py
> +    def __init__(self, w, text):
If the constructor doesn't really do anything, why it's there at all?

2021-11-23 09:54 UTC, pfalcon commented on picotui/widgets.py
> +        super().show_line('*'*len(l), i)
Please use spaces around `*`. Please use double-quote (`"`) for strings.

2021-11-23 10:32 UTC, timeopochin commented
No problem, I'm new to contributing, this is the first pull request I've ever done, I'll make those changes :) great project by the way, and looking forwards to 1.4/2.0

2021-11-25 15:16 UTC, timeopochin commented
I've made the changes, hope this is right :)

2021-11-25 16:37 UTC, pfalcon commented
Thanks for updates! I actually also meant update to commit message format to following existing format, but I did that myself. And while looking closer at it, I figured WPasswordEntry is to long, and shortened it to WPasswdEntry.

Merged with the above changes, thanks for the contribution!

2021-11-25 16:37 UTC, closed without merging

2021-11-25 17:21 UTC, timeopochin commented
Great, I'm glad I was able to contribute, I've found some bugs with the WTextEntry and WMultiEntry, whist testing it, I will open separate issues/fixing pull requests when I get the time :)